/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;
import java.awt.Image;
import java.awt.Graphics;
import java.beans.PropertyVetoException;
import java.sql.Connection;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import modulo.Conexao;
/**
 *
 * @author gabri
 */
public class JFramePrincipal extends javax.swing.JFrame {

    /**
     * Creates new form JFramePrincipal
     */
    private Connection conexao;
    public JFramePrincipal() {
        initComponents();
        this.setExtendedState(this.getExtendedState() | JFramePrincipal.MAXIMIZED_BOTH);
        try {
            Connection conn = Conexao.getConnection();
            conexao = conn;
        } catch (SQLException ex) {
            Logger.getLogger(JFramePrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        ImageIcon icon = new ImageIcon(getClass().getResource("/Imagem/fundo.jpg"));
        Image image = icon.getImage();
        jDesktopPane = new javax.swing.JDesktopPane(){
            public void paintComponent(Graphics g){
                g.drawImage(image, 0, 0, getWidth(), getHeight(), this);
            }
        };
        jMenuPrincipal = new javax.swing.JMenuBar();
        jMenuPrincipalVoltar = new javax.swing.JMenu();
        jMenuOperacoes = new javax.swing.JMenu();
        jMenuCadastrar = new javax.swing.JMenu();
        jMenuItemClienteCadastrar = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenuItemAmostraCadastrar = new javax.swing.JMenuItem();
        jMenuCaixaAnalise = new javax.swing.JMenu();
        jMenuItemCriarCaixa = new javax.swing.JMenuItem();
        jMenuItemCaixas = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("SOIL ANALYSIS");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        javax.swing.GroupLayout jDesktopPaneLayout = new javax.swing.GroupLayout(jDesktopPane);
        jDesktopPane.setLayout(jDesktopPaneLayout);
        jDesktopPaneLayout.setHorizontalGroup(
            jDesktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 981, Short.MAX_VALUE)
        );
        jDesktopPaneLayout.setVerticalGroup(
            jDesktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 628, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jDesktopPane)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jDesktopPane)
                .addContainerGap())
        );

        jDesktopPane.getAccessibleContext().setAccessibleDescription("");

        jMenuPrincipal.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N

        jMenuPrincipalVoltar.setText("Principal");
        jMenuPrincipalVoltar.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jMenuPrincipal.add(jMenuPrincipalVoltar);

        jMenuOperacoes.setText("Operações");
        jMenuOperacoes.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N

        jMenuCadastrar.setText("Cadastrar");

        jMenuItemClienteCadastrar.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jMenuItemClienteCadastrar.setText("Cliente");
        jMenuItemClienteCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemClienteCadastrarActionPerformed(evt);
            }
        });
        jMenuCadastrar.add(jMenuItemClienteCadastrar);
        jMenuCadastrar.add(jSeparator1);

        jMenuItemAmostraCadastrar.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jMenuItemAmostraCadastrar.setText("Amostra");
        jMenuItemAmostraCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemAmostraCadastrarActionPerformed(evt);
            }
        });
        jMenuCadastrar.add(jMenuItemAmostraCadastrar);

        jMenuOperacoes.add(jMenuCadastrar);

        jMenuCaixaAnalise.setText("Caixa de Análise");

        jMenuItemCriarCaixa.setText("Criar Caixa");
        jMenuItemCriarCaixa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCriarCaixaActionPerformed(evt);
            }
        });
        jMenuCaixaAnalise.add(jMenuItemCriarCaixa);

        jMenuOperacoes.add(jMenuCaixaAnalise);

        jMenuItemCaixas.setText("Caixas");
        jMenuItemCaixas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCaixasActionPerformed(evt);
            }
        });
        jMenuOperacoes.add(jMenuItemCaixas);

        jMenuPrincipal.add(jMenuOperacoes);

        setJMenuBar(jMenuPrincipal);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private static JInternalFrameClienteCadastrar cadastrarCliente;

    public static void resetarInternalCadastrarCliente() {
        cadastrarCliente = null;
    }

    private void jMenuItemClienteCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemClienteCadastrarActionPerformed

        if(evt.getSource() == jMenuItemClienteCadastrar){
            if(cadastrarCliente == null){
                cadastrarCliente = new JInternalFrameClienteCadastrar(jDesktopPane, conexao);
                jDesktopPane.add(cadastrarCliente).setVisible(true);
                cadastrarCliente.setPosicao();
            }
            else{
                try {
                    cadastrarCliente.moveToFront();
                    cadastrarCliente.setIcon(false);
                } catch (PropertyVetoException ex) {
                    Logger.getLogger(JFramePrincipal.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }
    }//GEN-LAST:event_jMenuItemClienteCadastrarActionPerformed

    private static JInternalFrameAmostraCadastrar cadastrarAmostra;
    
    public static void resetarInternalCadastrarAmostra() {
        cadastrarAmostra = null;
    }
    private void jMenuItemAmostraCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemAmostraCadastrarActionPerformed
        if (evt.getSource() == jMenuItemAmostraCadastrar) {
            if (cadastrarAmostra == null) {
                cadastrarAmostra = new JInternalFrameAmostraCadastrar(jDesktopPane, conexao);
                jDesktopPane.add(cadastrarAmostra).setVisible(true);
                cadastrarAmostra.setPosicao();
            } else {
                try {
                    cadastrarAmostra.moveToFront();
                    cadastrarAmostra.setIcon(false);
                } catch (PropertyVetoException ex) {
                    Logger.getLogger(JFramePrincipal.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }
    }//GEN-LAST:event_jMenuItemAmostraCadastrarActionPerformed

    
    private static JInternalFrameCriarCaixa criarCaixa;

    public static void resetarInternalCriarCaixa() {
        criarCaixa = null;
    }
    private void jMenuItemCriarCaixaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCriarCaixaActionPerformed
        if (evt.getSource() == jMenuItemCriarCaixa) {
            if (criarCaixa == null) {
                criarCaixa = new JInternalFrameCriarCaixa(jDesktopPane, conexao);
                jDesktopPane.add(criarCaixa).setVisible(true);
                criarCaixa.setPosicao();
            } else {
                try {
                    criarCaixa.moveToFront();
                    criarCaixa.setIcon(false);
                } catch (PropertyVetoException ex) {
                    Logger.getLogger(JFramePrincipal.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }
    }//GEN-LAST:event_jMenuItemCriarCaixaActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        fecharPrograma();
    }//GEN-LAST:event_formWindowClosing
    
    private static JInternalFrameCaixas caixas;

    public static void resetarInternalCaixas() {
        caixas = null;
    }
    private void jMenuItemCaixasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCaixasActionPerformed
        if (evt.getSource() == jMenuItemCaixas) {
            if (caixas == null) {
                caixas = new JInternalFrameCaixas(jDesktopPane, conexao);
                jDesktopPane.add(caixas).setVisible(true);
                caixas.setPosicao();
            } else {
                try {
                    caixas.moveToFront();
                    caixas.setIcon(false);
                } catch (PropertyVetoException ex) {
                    Logger.getLogger(JFramePrincipal.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }
    }//GEN-LAST:event_jMenuItemCaixasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFramePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFramePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFramePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFramePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFramePrincipal().setVisible(true);
            }
        });
    }
    public void fecharPrograma() {
        if (JOptionPane.showConfirmDialog(null,
                "Você tem certeza que quer fechar essa janela?", "Fechar?",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.QUESTION_MESSAGE) == JOptionPane.YES_OPTION) {
            try {
                conexao.close();
            } catch (SQLException ex) {
                Logger.getLogger(JFramePrincipal.class.getName()).log(Level.SEVERE, null, ex);
            }
            System.exit(0);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane jDesktopPane;
    private javax.swing.JMenu jMenuCadastrar;
    private javax.swing.JMenu jMenuCaixaAnalise;
    private javax.swing.JMenuItem jMenuItemAmostraCadastrar;
    private javax.swing.JMenuItem jMenuItemCaixas;
    private javax.swing.JMenuItem jMenuItemClienteCadastrar;
    private javax.swing.JMenuItem jMenuItemCriarCaixa;
    private javax.swing.JMenu jMenuOperacoes;
    private javax.swing.JMenuBar jMenuPrincipal;
    private javax.swing.JMenu jMenuPrincipalVoltar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
